/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "While this dialog is open, you can select two buildings to swap their positions at a cost of 5 Neurochrysalises. To do this, while this dialog is open, simply click on the buildings\n\t\t\tyou would like to swap, and the text below will change accordingly. You may have to move this dialog to see them.": "当此对话框打开时，您可以选择两个建筑物来交换它们的位置，费用为 5 个神经蛹。 为此，在此对话框打开时，只需单击要交换的建筑物\n\t\t\t，下面的文本将相应更改。 您可能必须移动此对话框才能看到它们。",
    "Upgrade Shop": "升级商店",
    "Upgrades": "升级",
    "Upgrading your habitation allows more people to take up residence in your Kingdom. Beware, however, that they will die if you don't have sufficient food.": "升级您的住所可以让更多人在您的王国居住。但是请注意，如果您没有足够的食物，它们会死亡。",
    "Vast Farm": "广阔的农场",
    "View Arcaneum": "查看奥秘",
    "View Army": "查看军队",
    "View Dragons": "查看龙",
    "View Machine Shop": "查看机械车间",
    "Water Shrine": "水神社",
    "Whirring gears and clanging metal create a violent symphony for miles around your machine shop.": "旋转的齿轮和叮当的金属在您的机械车间周围数英里内创造出暴力的交响乐。",
    "Wiki": "Wiki",
    "Woodpecker": "啄木鸟",
    "World Eater": "吞世者",
    "Wyvern": "飞龙",
    "Wyvern-Mount": "飞龙山",
    "You can automatically build up to 1 mechanical servant each second.": "您每秒最多可以自动构建 1 个机械仆从。",
    "You can not begin construction at the moment - your craftsmen are busy!": "您目前无法开始施工 - 您的工匠很忙！",
    "You can send people to be scholars - the more scholars you have the more you will discover. However, each new group you send will require one adamantium for tuition.": "您可以派人成为学者 - 您拥有的学者越多，您会发现的越多。但是，您发送的每个新组都需要一个 adamantium 来支付学费。",
    "You don't have a dragon. And everyone should have a dragon... also, how are you on this page? It doesn't unlock until you have a dragon. Dirty hacker.": "你没有龙。每个人都应该有一条龙……还有，你在这个页面上怎么样？在你有龙之前它不会解锁。肮脏的黑客。",
    "You found something!": "你发现了什么！",
    "You have decided to begin building an empire, and statues are a good way to remind the people who is in charge. If you build them across the land and send people to collect, you are bound to earn great riches.": "你已经决定开始建立一个帝国，雕像是提醒掌权者的好方法。如果你在陆地上建造它们并派人去收集，你一定会获得巨大的财富。",
    "You have entered the dwelling of the oracle of wisdom. Listen carefully, and your path shall be made clear.": "你已进入智慧神谕的居所。仔细聆听，你的道路将变得清晰。",
    "You have spent long enough sitting back and suffering relentless invasion. It is time to strike back - but be warned, you may be kicking the hornet's nest.": "你已经花了足够长的时间坐下来忍受无情的入侵。是时候反击了——但要注意，你可能是在踢马蜂窝。",
    "You're not sure how much work it will take to whip your people into a fighting force, but you have to start somewhere.": "你不确定将你的人民鞭打成一支战斗力量需要多少工作，但你必须从某个地方开始。",
    "Your Arcaneum is level 0 so each essence provides a 10% multiplier.": "你的奥秘是 0 级，所以每个精华提供 10% 的乘数。",
    "Your army strength is increased by 0% by memories of fallen comrades.": "阵亡战友的记忆使你的军队力量增加 0%。",
    "Your craftsmen can prepare this land for construction at a cost of 100K dirt per pixel. Be warned, however, that they will not\n\t\t\tbe able to repair your wall while they are working.": "您的工匠可以以每像素 100K 泥土的成本准备这片土地进行建设。但是请注意，他们在工作时将无法\n\t\t\t修复您的墙壁。",
    "Your delving mages have a 0% chance of finding 1 gem each second.": "你的钻探法师每秒有 0% 的几率找到 1 颗宝石。",
    "Your dragon can be fed any kind of essence. Once you select one, you will not be able to choose again. Choose wisely.": "你的龙可以被喂食任何种类的精华。一旦您选择了一个，您将无法再次选择。做出明智的选择。",
    "Remove Traps": "移除陷阱",
    "Reset": "重置",
    "Reset Game": "重置游戏",
    "Resources": "资源",
    "Resources Not Available": "资源不可用",
    "Rock Golem": "岩石魔像",
    "Sandshrew": "鼩鼱",
    "Save Game": "保存游戏",
    "Scholtek": "肖尔特克",
    "Seconds": "秒",
    "Select": "选择",
    "Select a gem from the list below - your gems will automatically be combined to form the selected gem. Note that the auto-smithy only combines gems, it cannot break them.": "从下面的列表中选择一颗宝石 - 您的宝石将自动组合成选定的宝石。 请注意，自动铁匠铺只能组合宝石，不能破坏它们。",
    "Send more Goblins!": "派出更多的哥布林！",
    "Send Your Dragon Through!": "送你的龙通过！",
    "Set Gem": "设置宝石",
    "Set Limit:": "设置限制：",
    "Shop": "店铺",
    "Smelting Pit": "冶炼坑",
    "Start Construction": "开始建设",
    "Stop Smelting!": "停止冶炼！",
    "Structures": "结构",
    "Subreddit": "子版块",
    "Take a look!": "看一看！",
    "The center of life in your kingdom.": "你王国的生活中心。",
    "The Golden Well": "金井",
    "The halls of higher learning glow with the furthering of civilization.": "高等学堂随着文明的进步而熠熠生辉。",
    "The technological age has begun to dawn in your kingdom, and with a little bit of magic, your mechanists believe they can make some of your servants a tad more obsolete.": "你的王国已经开始进入科技时代，只要有一点魔法，你的机械师相信他们可以让你的一些仆人变得更加过时。",
    "Titan of Earth": "地球泰坦",
    "Toggle navigation": "切换导航",
    "Trade Amount:": "交易金额：",
    "Train your Hunters!": "训练你的猎人！",
    "Train your soldiers!": "训练你的士兵！",
    "Traps": "陷阱",
    "Try buying a new one.": "试着买一个新的。",
    "University": "大学",
    "Update!": "更新！",
    "Upgrade": "升级",
    "Upgrade Cost:": "升级费用：",
    "Your pick has no sockets!": "你的选择没有插槽！",
    "Your rock golems slave away in the hot sun deep in the quarry. Keep checking back, perhaps they'll find something.": "你的石傀儡在采石场深处的烈日下苦苦挣扎。继续检查，也许他们会找到一些东西。",
    "Pickaxe Sockets": "镐槽",
    "Pile It On!": "把它堆起来！",
    "Prepare Land": "准备土地",
    "Product": "产品",
    "Projects": "项目",
    "Pry Gems From Pick": "从 Pick 中撬出宝石",
    "Quarry": "采石场",
    "Rare Materials": "稀有材料",
    "Ratio": "比率",
    "Raw Materials": "原料",
    "Reactant": "反应物",
    "Recipes": "食谱",
    "Regal Statue": "富豪雕像",
    "Release Notes": "发行说明",
    "Remove Lures": "移除诱饵",
    "Flawed": "有缺陷的",
    "Flawless": "完美无瑕",
    "Fletcher": "弗莱彻",
    "For Hire": "出租",
    "Games": "游戏",
    "Gem Sales": "宝石销售",
    "Gem:": "宝石：",
    "Gems": "宝石",
    "General": "一般的",
    "Go!": "去！",
    "Goblin": "地精",
    "Gold": "金子",
    "Graveyard": "墓地",
    "Great": "伟大的",
    "Habitation": "居住地",
    "Hireling Imbuement": "雇佣灌输",
    "Hirelings": "雇佣兵",
    "Hive Queen": "蜂巢女王",
    "If your population gets too high, you might not be able to feed them all. As a leader you may have to make the hard decision of sending them into exile.": "如果你的人口太高，你可能无法养活他们。作为领导者，您可能不得不做出将他们流放的艰难决定。",
    "Import Save": "导入保存",
    "Industrial District": "工业区",
    "Initiate Blind Revenge": "发起盲目复仇",
    "It is rumored that mages of great power can be hired... but you lack gold.": "有传言说可以雇佣强大的法师……但你缺金子。",
    "Large Ant": "大蚂蚁",
    "Latin-Like Unicode Generator": "拉丁风格的 Unicode 生成器",
    "Launch campaign!": "发起活动！",
    "Leave Oracle": "离开甲骨文",
    "Lightning Shrine": "闪电神殿",
    "Links:": "链接：",
    "Loading Mine Defense...": "正在加载矿山防御...",
    "Lures": "诱饵",
    "Machine Shop": "机器商店",
    "Machinist": "机械师",
    "Mage Deployment": "法师部署",
    "Mage Tower": "法师塔",
    "Mage Upgrades": "法师升级",
    "Mages bustle about, speaking softly to each other, and a magical aura seems to emanate from deep within.": "法师们熙熙攘攘，彼此轻声说话，一股神奇的气息似乎从内心深处散发出来。",
    "Majestic": "雄伟",
    "Make a Wish!": "许个愿！",
    "Mana": "法力",
    "Math Art Sandbox": "数学艺术沙盒",
    "Mecha-Mages": "机械法师",
    "Men At Work": "在工作的男人们",
    "Military Campaigns": "军事行动",
    "Mine Defense": "矿山防御",
    "Mine Defense Menu": "矿山防御菜单",
    "Mine Defense Stats": "矿山防御统计",
    "Miner": "矿工",
    "More Power!": "更多力量！",
    "Move Structures": "移动结构",
    "Move!": "移动！",
    "Murky": "阴暗",
    "Neurochrysalis": "神经蛹",
    "New Homes:": "新房：",
    "No campaigns have been launched.": "没有发起任何活动。",
    "No Dragon": "没有龙",
    "None": "无",
    "Normal": "普通",
    "Now that the land is prepared, you can begin construction on it. Below is a list of available structures and their prices.": "现在土地已经准备好，你可以开始在上面建造了。以下是可用结构及其价格的列表。",
    "Short Scale": "短比例",
    "Oracle of Wisdom": "智慧神谕",
    "Make a Wish! (1DuTri Gold)": "许个愿！ (1DuTri 黄金)",
    "Dark Mages can gift your workers with unnatural abilities. But the energy costs are great.\n\t\t\t\t\t\t\tAnd this mine is beginning to feel a little dark.": "黑暗法师可以赋予你的工人非自然的能力。 但是能源成本很高。\n\t\t\t\t\t\t\t而且这个矿山开始感觉有点暗。",
    "Defense": "防御",
    "Dimensional Rift": "次元裂隙",
    "Disable Click Effects": "禁用点击效果",
    "Disable Notifications": "禁用通知",
    "Disciplines": "学科",
    "Dragon Hunter": "猎龙者",
    "Dragon Nest": "龙巢",
    "Dragons": "龙",
    "Dragons also have an active effect only while you have that dragon.": "龙也只有当你拥有那条龙时才会有主动效果。",
    "Dreary": "凄凉",
    "Exchange Market": "交易市场",
    "Expand Your Empire!": "扩展你的帝国！",
    "Expand your fields!": "扩大你的领域！",
    "Expanded Farm": "扩大农场",
    "Export Code": "导出代码",
    "Export Save": "导出保存",
    "Essence": "本质",
    "Essence Allocated": "分配的精华",
    "Earth Shrine": "大地神殿",
    "Enable Blind Revenge": "启用盲目复仇",
    "Feed X Times (XM Food)": "喂食 X 次 (XM Food)",
    "Feed Your Dragon": "喂你的龙",
    "Fire Shrine": "火神殿",
    "Fire swirls around the central orb in front of a bone white sculpture radiating power. Your mages seem to be tapping into it somehow...": "一个散发着力量的骨白色雕塑前面的中央球体周围有火焰旋转。 你的法师似乎正在以某种方式利用它......",
    "Hone Weapons (1 Adamantium, 100 Steel)": "磨练武器（1 精金，100 钢）",
    "Perfect": "完美的",
    "Run Auto-Rift 9000! (13 Mages)": "运行 自动裂痕 9000！ (13 法师)",
    "Save Successful": "保存成功",
    "Send Scouts! (5 Craftsmen)": "派侦察兵！ (5名工匠)",
    "Smithy Power: 10 gems/second": "铁匠铺力量：10 宝石/秒",
    "- 1 level per click.": "- 每次点击 1 级。",
    "\"It is rumored that mages of great power can be hired... but you lack gold.\"": "“传闻可以雇佣大法师……但你缺金子。”",
    "Number to Combine/Break:": "要组合/断开的数量：",
    "Number to Exile:": "流放人数：",
    "Number to Move:": "移动号码：",
    "Scholars:": "学者：",
    "A bustling field growing a strange blue fruit.": "繁华的田野里长着一种奇怪的蓝色水果。",
    "A bustling field growing a strange blue fruit. For some reason this farm produces slightly more flax.": "繁华的田野里长着一种奇怪的蓝色水果。出于某种原因，这个农场生产的亚麻稍微多一些。",
    "A bustling field growing a strange blue fruit. Occasionally you find a few sprigs of flax as well.": "繁华的田野里长着一种奇怪的蓝色水果。偶尔你也会发现几枝亚麻。",
    "A bustling market filled with exotic food and rare minerals. You can trade various resources here, but be warned, prices change often and they aren't always fair! Click the buttons to trade!": "充满异国情调的食物和稀有矿物的繁华市场。您可以在这里交易各种资源，但请注意，价格经常变化，而且并不总是公平的！点击按钮进行交易！",
    "A dark place where nightmarish goblins toil day and night over vats of hot metal.": "一个黑暗的地方，噩梦般的地精日夜在滚烫的金属桶上辛勤劳作。",
    "A flashing vortex of electricity fills the orb in front of the statue. You feel a desire for greater riches overwhelming you as you approach.": "一道闪烁的电流漩涡充满了雕像前面的球体。当你接近时，你会感到对更大财富的渴望压倒了你。",
    "A flurry of activity fills the halls as scores of accountants attempt to keep track of all the resources coming from such odd sources.": "当数十名会计师试图跟踪来自这些奇怪来源的所有资源时，大厅里充满了一系列活动。",
    "A large egg perches comically among the dirt and straw. What could possibly sleep within?": "一个大鸡蛋滑稽地栖息在泥土和稻草之间。什么可能睡在里面？",
    "A large mound of rock sits plainly in a fenced compound. Have you considered adding some gold?": "一大堆岩石平躺在一个有围栏的院子里。您是否考虑过添加一些黄金？",
    "A looming library filled with ancient tomes and an aura of knowledge. It is said that one who masters these halls is bound by nothing.": "一个隐约可见的图书馆，里面充满了古老的书籍和知识的光环。据说，掌握了这些殿堂的人，便不受任何束缚。",
    "A massive rift to another dimensions pulses violently on a stone platform. All adult dragons have a desire to pass through...": "巨大的异次元裂隙在石台上剧烈地跳动着。所有成年龙都有穿越的欲望……",
    "A quaking vortex of earth fills the orb in front of the statue. When you stand near it, you begin to understand the pickaxe in your hands on a new level.": "一个颤抖的地球漩涡充满了雕像前面的球体。当你站在它附近时，你开始对手中的镐有了一个新的认识。",
    "A skeleton of adamantium, a heart and soul of gem-bound magic, a body of water, and a deep knowledge of the elements for their science.": "精金骨架、宝石绑定魔法的核心和灵魂、水体以及对科学元素的深入了解。",
    "A skeleton of adamantium, a heart and soul of gem-bound magic, a body of water, and fire and earth to practice their trade.": "一具精金骷髅，一颗镶嵌宝石的魔法之心和灵魂，一身水，还有火与土来练习他们的交易。",
    "A skeleton of adamantium, a heart and soul of gem-bound magic, a body of water, and just enough flame to deal some damage.": "一具精金骨架，一颗宝石绑定魔法的心脏和灵魂，一团水，以及足以造成一些伤害的火焰。",
    "A somber field, wrapped in memory. Here your soldiers draw strength from memory and wish for revenge.": "一片阴郁的田野，被记忆包裹着。在这里，您的士兵从记忆中汲取力量并希望复仇。",
    "A team of skilled craftsmen make bowstrings to send out your bravest men and women to hunt dragons. You can now hire them, but they don't come cheap!": "一队熟练的工匠制作弓弦，派出最勇敢的男人和女人去猎龙。您现在可以雇用他们，但他们并不便宜！",
    "A whirling vortex of water fills the dark orb in front of the statue. The air around it feels cold, and... moist. Your alchemists spend an unusual amount of time near it...": "一个旋转的水漩涡充满了雕像前的黑暗球体。它周围的空气感觉寒冷，而且……潮湿。你的炼金术士在它附近花费了不寻常的时间......",
    "About Me": "关于我",
    "Administration Building": "行政楼",
    "Alchemy": "炼金术",
    "All": "全部",
    "An uncomfortable heat hangs over the ground, and a gruff, solid man grunts at you to say what you need.": "一股不舒服的热气笼罩着地面，一个粗鲁、结实的男人向你咕哝着说你需要什么。",
    "Arcaneum": "奥秘",
    "Auto-Smithy": "自动铁匠铺",
    "Automated-Alchemists": "自动炼金术士",
    "Barracks": "兵营",
    "Basic (Gold/Mana)": "基础（金/法力）",
    "Black Hole Filler Extreme": "黑洞填充极端",
    "Blacksmith": "铁匠",
    "Blind revenge is disabled.": "盲目报复被禁用。",
    "Blog": "博客",
    "Bloodhound": "寻血猎犬",
    "Bomb Enemies (100 Mana)": "轰炸敌人 (100 法力)",
    "Build": "建造",
    "Build Alchemist (50K Adamantium, 1B Majestic Gems, 10 Water Essence, 10 Fire Essence, 10 Earth Essence, 10 Lightning Essence)": "Build Alchemist (50K Adamantium, 1B Majestic Gems, 10 Water Esence, 10 Fire Esence, 10 Earth Esence, 10 Lightning Esence)",
    "Build Craftsman (50K Adamantium, 500M Majestic Gems, 5 Water Essence, 5 Fire Essence, 5 Earth Essence)": "Build Craftsman (50K Adamantium, 500M Majestic Gems, 5 Water Esence, 5 Fire Esence, 5 Earth Esence)",
    "Build Mage (50K Adamantium, 1B Majestic Gems, 10 Water Essence, 10 Fire Essence)": "Build Mage (50K Adamantium, 1B Majestic Gems, 10 Water Esence, 10 Fire Esence)",
    "Build Stick Wall (100K gold)": "建造棒墙（100K金）",
    "Campaign Results": "活动结果",
    "Cancel": "取消",
    "Change Imbue Amount": "改变灌输量",
    "Close Alchemy Window": "关闭炼金术窗口",
    "Close Industry Screen": "关闭行业屏幕",
    "Close Mage Window": "关闭法师窗口",
    "Close Menu": "关闭菜单",
    "Close Military Screen": "关闭军事屏幕",
    "Close Stats": "关闭统计",
    "Collecting data...": "收集数据...",
    "Combine All": "结合所有",
    "Combine Up To:": "合并到：",
    "Cracked": "破裂",
    "Crafting": "制作",
    "Cyber-Craftsmen": "网络工匠",
    "Data Display:": "数据显示：",
    "Data Refresh:": "数据刷新：",
    "Exceptional": "卓越",
    "Farm": "农场",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    't': 't',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t\t": "\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Upgrades Bought: ": "购买的升级：",
    "Upgrades Remaining: ": "剩余升级：",
    "Wall Fortifications: ": "城墙防御：",
    "Wall: ": "城墙：",
    "Water Essence: ": "水之精华：",
    "Wyvern Boost: ": "飞龙强化：",
    "Treasures Found: ": "发现的宝藏：",
    "Total Water Essence: ": "总计水之精华：",
    "Total Traps Bought: ": "购买的陷阱总数：",
    "Total Time: ": "总时间：",
    "Total Craftsmen: ": "总计工匠：",
    "Total Alchemists: ": "总计炼金术士：",
    "Total Earth Essence: ": "总计地之精华：",
    "Total Lightning Essence: ": "总计雷电精华：",
    "Total Spirit Essence: ": "总计精神精华：",
    "Total Fire Essence: ": "总计火之精华：",
    "Total Adamantium: ": "总计精金：",
    "Total Industry Level: ": "总计工业等级：",
    "Total Lures Bought: ": "总计购买诱饵：",
    "Total Non-Ant Hirelings: ": "总计非蚂蚁雇工：",
    "Total Steel: ": "总计钢：",
    "Total Mages: ": "总计法师：",
    "Total Mana: ": "总计法力：",
    "Total Iron: ": "总计铁：",
    "Total Coal: ": "总计煤炭：",
    "Total Dirt: ": "总计泥土：",
    "Total Food: ": "总计食物：",
    "Total Stone: ": "总计石头：",
    "Total Imbuements: ": "总计灌注：",
    "Total Gems: ": "总计宝石：",
    "Total Gold: ": "总计黄金：",
    "Training Cost: ": "训练成本：",
    "Lightning Essence: ": "雷电精华：",
    "Mage Wisdom Level: ": "法师智慧等级：",
    "Majestic Gems: ": "雄伟宝石：",
    "Majestic: ": "雄伟：",
    "Mages Fighting: ": "法师格斗：",
    "Mages Delving: ": "法师钻研：",
    "Perfect Gems: ": "完美宝石：",
    "Population: ": "人口：",
    "Perfect: ": "完美：",
    "Version ": "版本 ",
    "Soldiers Lost: ": "士兵损失：",
    "Spiders Killed: ": "杀死的蜘蛛：",
    "Spirit Essence: ": "精神精华：",
    "Tool: Hands ": "工具：手",
    "Tool: Stick ": "工具：棍子",
    "Mana Multiplier: ": "法力乘数：",
    "Mana: ": "法力：",
    "Manual Clicks: ": "手动点击：",
    "Market Trades: ": "市场交易：",
    "Murky Gems: ": "黑暗宝石：",
    "Murky: ": "黑暗：",
    "Normal Gems: ": "普通宝石：",
    "Normal: ": "普通：",
    "Flawed Gems: ": "瑕疵宝石：",
    "Flawed: ": "瑕疵：",
    "Flawless Gems: ": "无瑕宝石：",
    "Flawless: ": "无暇：",
    "Food After Upgrade: ": "升级后的食物：",
    "Force Control (Multibuy): ": "强制控制（批量购买）：",
    "Goblins Killed: ": "杀死的哥布林：",
    "Goblins Sacrificed: ": "牺牲的哥布林：",
    "Gold Per Second: ": "每秒的黄金：",
    "Gold: ": "黄金：",
    "Great Gems: ": "伟大宝石：",
    "Great: ": "伟大：",
    "Harvest Data: ": "收获数据：",
    "Highest Dragon Level: ": "最高龙等级：",
    "Number Format: ": "数字格式：",
    "Dreary Gems: ": "凄凉宝石:",
    "Dreary: ": "凄凉：",
    "Dragons Sacrificed: ": "牺牲的龙：",
    "Dragon Level: ": "龙等级：",
    "Earth Essence: ": "地之精华：",
    "Education Level: ": "教育等级：",
    "Enemy Strength: ": "敌方实力：",
    "Essence Multiplier: ": "精华乘数：",
    "Exceptional Gems: ": "卓越宝石：",
    "Exceptional: ": "卓越：",
    "Mages Meditating: ": "冥想法师：",
    "Fire Essence: ": "火之精华：",
    "Socket ": "插槽 ",
    "Current Mage Power: ": "当前法师力量：",
    "Cracked Gems: ": "破裂宝石：",
    "Cracked: ": "破裂：",
    "Combinations Limit: ": "组合上限：",
    "Campaigns Won: ": "赢得的活动：",
    "Automatic Clicks: ": "自动点击：",
    "Available Soldiers: ": "可用士兵：",
    "Average Market Boost: ": "平均市场提升：",
    "Auto-Auto Rift: ": "自动-自动裂隙：",
    "Army Strength: ": "军队实力：",
    "Alchemical Speed: ": "炼金术速度：",
    "Alchemist's Potential: ": "炼金术士潜能：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^([\d\.,]+) out of ([\d\.,]+)$/, '$1 \/ $2'],
    [/^Your dragon is level (.+). That's kind of sad. I bet the other dragons make fun of it.$/, '你的龙是 $1 级。这有点可悲。 我敢打赌其他龙会取笑它。'],
    [/^Your dragon is level (.+). They grow up so fast!$/, '你的龙是 $1 级。它们成长地好快！'],
    [/^New merchants with new prices will arrive in (.+) seconds!$/, '新商家带着新价格 $1 秒后到达！'],
    [/^Your smelting pit has a chance of producing (.+) adamantium.$/, '你的冶炼坑有几率产生 $1 精金。'],
    [/^(.+) times Gold Per Second$/, '每秒 $1 次黄金'],
    [/^(.+) Steel, (.+) Food, (.+) Gold$/, '$1 钢、$2 食物、$3 黄金'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) \(next after ([\d\.]+) goblin\)$/, '$1 （下一个在 $2 哥布林之后）'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) food every 60 seconds$/, '$1 食物每 60 秒'],
    [/^([\d\.,]+) Food$/, '$1 食物'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\- ([\d\.,]+) levels per click.$/, '\- 每次点击 $1 级'],
    [/^Building ([\d\.,]+): None$/, '建筑 $1： 无'],
    [/^(.+) Large Ants   \-   (.+) hired$/, '$1 大蚂蚁   \-   $2 已雇佣'],
    [/^(.+) Gold   \-   (.+) hired$/, '$1 黄金   \-   $2 已雇佣'],
    [/^(.+) Mana   \-   (.+) hired$/, '$1 法力   \-   $2 已雇佣'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Upgrade Cost: (.+) Dragonscale$/, '升级成本：$1 龙鳞'],
    [/^Upgrade Cost: (.+) Flax$/, '升级成本：$1 亚麻'],
    [/^Upgrade Cost: (.+) Food$/, '升级成本：$1 食物'],
    [/^Upgrade Cost: (.+) Iron$/, '升级成本：$1 铁'],
    [/^Upgrade Cost: (.+) Dirt$/, '升级成本：$1 泥土'],
    [/^Upgrade Cost: (.+) Stone$/, '升级成本：$1 石头'],
    [/^Upgrade Cost: (.+) Steel$/, '升级成本：$1 钢'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Time: (.+) hour, (.+) minutes, (.+) second$/, '时间：$1 小时，$2分，$3 秒'],
    [/^Time: (.+) minutes, (.+) seconds$/, '时间：$1 分，$2 秒'],
    [/^Time: (.+) minutes, (.+) second$/, '时间：$1 分，$2 秒'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);